server:
  port: 8080

spring:
#  ------- db config -------
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true

#  ------- kafka config -------
  kafka:
    bootstrap-servers: localhost:9092
    topic: user-info
    consumer:
      group-id: user-info
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.tasnim.userservice.deserializer.UserInfoDeserializer